### ISSUE TITLE
feature request Endianness

### ISSUE THREAD

**Issue by nissaba** [den0206/ble_data_converter#4]
I was using your package and notived that there is not way to set the endianness of the data to be transfered. 
My Ble device is using Big endian and the mobiles are on little endian. So it would be nice in the case you have to work with a big endian system to be able to set that endianness

**Comment by nissaba** [comment]
possibly something like this 

 library ble_data_converter;

import 'dart:convert';
import 'dart:math';
import 'dart:typed_data';

enum BLEDataConverter {
  str,
  i8,
  i16,
  i32,
  i64,
  u8,
  u16,
  u32,
  u64;

  int get _byteSize {
    switch (this) {
      case BLEDataConverter.i8:
      case BLEDataConverter.u8:
        return 1;
      case BLEDataConverter.i16:
      case BLEDataConverter.u16:
        return 2;
      case BLEDataConverter.i32:
      case BLEDataConverter.u32:
        return 4;
      case BLEDataConverter.i64:
      case BLEDataConverter.u64:
        return 8;
      default:
        throw AssertionError();
    }
  }

  List<int> stringToUtf8(String value) {
    if (this == str) {
      return utf8.encode(value);
    } else {
      throw AssertionError();
    }
  }

  String stringFromUtf8(List<int> bytes) {
    if (this == str) {
      return utf8.decode(bytes);
    } else {
      throw AssertionError();
    }
  }

  Uint8List intToBytes(int value, {bool bigEndian = true}) {
    final u8List = Uint8List(_byteSize);
    final data = u8List.buffer.asByteData();

    switch (this) {
      case BLEDataConverter.i8:
        data.setInt8(0, value);
        break;
      case BLEDataConverter.i16:
        data.setInt16(0, value, bigEndian ? Endian.big : Endian.little);
        break;
      case BLEDataConverter.i32:
        data.setInt32(0, value, bigEndian ? Endian.big : Endian.little);
        break;
      case BLEDataConverter.i64:
        data.setInt64(0, value, bigEndian ? Endian.big : Endian.little);
        break;
      case BLEDataConverter.u8:
        data.setUint8(0, value);
        break;
      case BLEDataConverter.u16:
        data.setUint16(0, value, bigEndian ? Endian.big : Endian.little);
        break;
      case BLEDataConverter.u32:
        data.setUint32(0, value, bigEndian ? Endian.big : Endian.little);
        break;
      case BLEDataConverter.u64:
        data.setUint64(0, value, bigEndian ? Endian.big : Endian.little);
        break;
      default:
        throw AssertionError();
    }

    return u8List;
  }

  int bytesToInt(List<int> bytes, {bool bigEndian = true}) {
    if (this == BLEDataConverter.str) {
      throw AssertionError();
    }
    
    var byteData = ByteData.sublistView(Uint8List.fromList(bytes));
    switch (this) {
      case BLEDataConverter.i8:
        return byteData.getInt8(0);
      case BLEDataConverter.i16:
        return byteData.getInt16(0, bigEndian ? Endian.big : Endian.little);
      case BLEDataConverter.i32:
        return byteData.getInt32(0, bigEndian ? Endian.big : Endian.little);
      case BLEDataConverter.i64:
        return byteData.getInt64(0, bigEndian ? Endian.big : Endian.little);
      case BLEDataConverter.u8:
        return byteData.getUint8(0);
      case BLEDataConverter.u16:
        return byteData.getUint16(0, bigEndian ? Endian.big : Endian.little);
      case BLEDataConverter.u32:
        return byteData.getUint32(0, bigEndian ? Endian.big : Endian.little);
      case BLEDataConverter.u64:
        return byteData.getUint64(0, bigEndian ? Endian.big : Endian.little);
      default:
        throw AssertionError();
    }
  }

  DateTime byteOfMillisecondsToDatetime(List<int> bytes, {bool bigEndian = true}) {
    final intValue = bytesToInt(bytes, bigEndian: bigEndian);
    return DateTime.fromMillisecondsSinceEpoch(intValue);
  }

  DateTime byteOfMicrosecondsToDatetime(List<int> bytes, {bool bigEndian = true}) {
    final intValue = bytesToInt(bytes, bigEndian: bigEndian);
    return DateTime.fromMicrosecondsSinceEpoch(intValue);
  }
}

**Comment by den0206** [comment]
@nissaba 
Try using the following ref.Endian Type to add a branch.
`
 ble_data_converter:
    git:
      url: git@github.com:den0206/ble_data_converter.git
      ref: f06f4dd0f9d98e6b772055037c7b82e2fec72d4c
`

If available, this change will be incorporated into the Ver_1.0.0 update ;
Thanks.

**Comment by den0206** [comment]
@nissaba 
The issue has been closed.
Please try using [Ver_1.0.0](https://pub.dev/packages/ble_data_converter).

``` dart
// encode(Little-endian)
  final int i64Max = 9223372036854775807;
  final List<int> value =
      BLEDataConverter.i64.intToBytes(i64Max, endian: Endian.little);

  print(value); //[127, 255, 255, 255, 255, 255, 255, 255]

  // decode(Little-endian)
  final int decode =
      BLEDataConverter.i64.bytesToInt(value, endian: Endian.little);

  print(decode); // 9223372036854775807
```
